config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'application#index'
  resources :users, only: [:index]
  post '/users/search_by', to: 'users#search_by'
  get '/users/new', to: 'admin/users#new'
  get '/workshops/new', to: 'admin/workshops#new'

  authenticate :user do
    resources :users, only: [:show]
    resources :skills, only: [:edit, :destroy]
    resources :workshops, except: [:new, :create] do
      resources :skills, only: [:new, :create, :edit, :update, :destroy]
      resources :users, only: [:show, :edit, :update]
    end
  end

  namespace :admin  do
    resources :users, only: [:show, :edit, :update]
    resources :workshops, only: [:new, :create, :edit, :update]
  end
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  has_many :skills
  has_many :users, through: :skills
  belongs_to :officer, class_name: 'User', foreign_key: 'user_id'

  accepts_nested_attributes_for :skills, allow_destroy: true,  :reject_if => proc { |attributes| attributes['title'].blank? }

  validates :name, presence: :true, uniqueness: :true

  def self.total_workshops
    count
  end

  def user_id=(officer_id)
    officer = User.find_by(id: officer_id)
    self.officer = officer
    self.skills.each do |skill|
      if !officer.skills.include?(skill)
        officer.skills << skill
      end
      UserSkill.find_by(user_id: officer.id, skill_id: skill.id).make_expert
    end
    officer
  end

  def expert?(user)
      self.skills.all? { |skill| Skill.experts(skill).include?(user) }
  end
end

app/controllers/admin/workshops_controller.rb
class Admin::WorkshopsController < AdminController
  before_action :set_workshop, only: [:edit, :update]
  def new
    @workshop = Workshop.new
  end

  def create
    @workshop = Workshop.new(workshop_params)
    if @workshop.save
      redirect_to @workshop, notice: 'Workshop created successfully'
    else
      render action: 'new', alert: "Creation failed:  #{@workshop.errors.full_messages}"
    end
  end

  def edit
    @workshop = Workshop.find_by(id: params[:id])
  end

  def update
    if @workshop.update(workshop_params)
      redirect_to @workshop, notice: 'Workshop updated'
    else
      render action: 'edit', alert: "Update failed:  #{@workshop.errors.full_messages}"
    end
  end

  private
  def workshop_params
    params.require(:workshop).permit(:name, :user_id, :skills_attributes => [:title, :content, :_destroy])
  end

  def set_workshop
    @workshop = Workshop.find(params[:id])
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :is_officer?]
  before_action :is_officer?, only: [:edit, :new, :update, :create]

  def index
    if params[:user_id]
      @workshops = User.find_by(id: params[:user_id]).workshops
    else
      @workshops = Workshop.all
    end
  end

  def show
  end

  def edit
  end

  def update
    if @workshop.update(workshop_params)
      redirect_to @workshop, notice: 'Workshop updated'
    else
      render action: 'edit', alert: "Update failed:  #{@workshop.errors.full_messages}"
    end
  end

  private
  def set_workshop
    @workshop = Workshop.find(params[:id])
  end

  def workshop_params
    params.require(:workshop).permit(:name, :user_id, :skill_ids=> [], :skills_attributes => [:title, :content, :_destroy])
  end
end

app/views/workshops/_form.html.erb
<%= form_for @workshop do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @workshop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <h3><%= f.object.name%></h3>

  <h4> Skills: </h4>
  <% if @workshop.skills.size == 0 %>
      No skills found.
  <% else %>
    <div class="field checkbox-list well">
      <%= f.collection_check_boxes :skill_ids, @workshop.skills, :id, :title %>
    </div>
  <%end%>

  <h4>Create new skill(s): <h4>
  <div class="form-group">
    <%= f.nested_fields_for :skills, @workshop.skills.build do |skills_fields| %>
      <%= skills_fields.remove_nested_fields_link %>

      <%=skills_fields.label :title %>
      <%=skills_fields.text_field :title %>

      <%=skills_fields.label :description %>
      <%=skills_fields.text_field :description %>
    <% end %>
    <%= f.add_nested_fields_link :skills %>
  </div>

  <div class="actions">
   <%= f.submit %>
 </div>

<% end %>

app/views/workshops/edit.html.erb
Edit Workshop

<%= render 'form' %>

app/views/workshops/index.html.erb
<% if is_admin? %>
  <%= link_to "Create New Workshop", new_admin_workshop_path, class: "btn btn-primary" %>
<% end %>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @workshops.each do |workshop| %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading<%=workshop.id%>">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=workshop.id%>" aria-expanded="false" aria-controls="collapse<%=workshop.id%>">
          <%=workshop.name %> (Click to view skills) <%= link_to "View Workshop", workshop_path(workshop), class: "btn btn-info"  %>
        </a>
      </h4>
    </div>
    <div id="collapse<%=workshop.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=workshop.id%>">
      <div class="panel-body">
        <% if workshop.skills.size == 0 %>
            No skills for this workshop
        <% end %>
        <% workshop.skills.each do |skill| %>
          <% if is_officer?(workshop) %>
            <li><%= link_to skill.title, edit_workshop_skill_path(workshop, skill) %></li>
          <% else %>
            <li  class= "<%=current_user.skill_level(skill)%>" ><%= skill.title %></li>
          <%end%>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

  <% if is_admin? %>
    <% if !Skill.unassigned.empty? %>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOther">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOther" aria-expanded="false" aria-controls="collapseOther">
            Unassigned Skills (Click to view skills)
          </a>
        </h4>
      </div>
      <div id="collapseOther" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOther">
        <div class="panel-body">
          <% Skill.unassigned.each do |skill| %>
              <li><%= link_to skill.title, edit_skill_path(skill), class: "#{current_user.skill_level(skill)}"  %></li>
            <%end%>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>

</div>

app/views/workshops/show.html.erb
<h1><%= @workshop.name %> </h2>
<% if !@workshop.officer.nil? %>
  <h3><%= "Officer: #{@workshop.officer.name}"%></h3>
<%end%>
<% if is_officer? && !is_admin? %>
  <%= link_to "Add New Skill", new_workshop_skill_path(@workshop), class: "btn btn-primary"  %>
  <%= link_to "Edit Workshop", edit_workshop_path(@workshop), class: "btn btn-primary"  %>
<% end %>
<% if is_admin? %>
  <%= link_to "Add New Skill", new_workshop_skill_path(@workshop), class: "btn btn-primary"  %>
  <%= link_to "Edit Workshop", edit_admin_workshop_path(@workshop), class: "btn btn-primary"  %>
<% end %>
<table class="table table-bordered table-striped">
  <thead>
    <caption>Required Skills</caption>
    <tr>
      <th>Title</th>
      <th>Experts</th>
      <% if is_officer? || is_admin? %>
        <th>Edit</th>
        <th>Delete</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% if @workshop.skills.size == 0 %>
      <tr>
        <td colspan="6">No skills found.
          <% if is_officer? || is_admin? %>
            <%= link_to "Create New Skill", new_workshop_skill_path(@workshop), class: "btn btn-primary"%>
          <%end%>
        </td>
      </tr>
    <% else %>
      <%@workshop.skills.each do |skill|%>
      <tr>
        <td><%=skill.title%> </td>
        <td><%=Skill.experts(skill).pluck(:name).join(", ")%> </td>
        <% if is_officer? || is_admin? %>
          <td><%= link_to "Edit Skill", edit_workshop_skill_path(@workshop, skill), class: "btn btn-warning"  %> </td>
          <td><%= link_to "Remove Skill", workshop_skill_path(@workshop, skill), :method => :delete, class: "btn btn-danger"  %> </td>
        <% end %>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>