config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'application#index'
  resources :users, only: [:index]
  post '/users/search_by', to: 'users#search_by'
  get '/users/new', to: 'admin/users#new'
  get '/workshops/new', to: 'admin/workshops#new'

  authenticate :user do
    resources :users, only: [:show]
    resources :skills, only: [:edit, :destroy]
    resources :workshops, except: [:new, :create] do
      resources :skills, only: [:new, :create, :edit, :update, :destroy]
      resources :users, only: [:show, :edit, :update]
    end
  end

  namespace :admin  do
    resources :users, only: [:show, :edit, :update]
    resources :workshops, only: [:new, :create, :edit, :update]
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :workshop, optional: true
  has_many :user_skills
  has_many :users, through: :user_skills

  validates :title, presence: true, uniqueness: true

  def self.unassigned
    self.where(workshop_id: nil)
  end

  def self.experts(skill)
    User.joins(:user_skills).where(user_skills: {skill_level: :expert, skill_id: skill.id})
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  def new
    @workshop = Workshop.find_by(id: params[:workshop_id])
    @skill = Skill.new(workshop_id: params[:workshop_id])
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to workshop_path(@skill.workshop_id), notice: 'New skill created successfully'
    else
      @workshop = Workshop.find_by(id: params[:workshop_id])
      render action: 'new', alert: "Creation failed:  #{@skill.errors.full_messages}"
    end
  end

  def edit
    @workshop = Workshop.find_by(id: params[:workshop_id])
  end

  def update
    if @skill.update(skill_params)
      redirect_to workshop_path(@skill.workshop_id), notice: 'Skill updated'
    else
      render action: 'edit', alert: "Update failed: #{@skill.errors.full_messages}"
    end
  end

  def destroy
    @workshop = @skill.workshop
    @skill.destroy
    if !!@workshop
      redirect_to workshop_path(@workshop), notice: 'Skill deleted'
    else
      redirect_to workshops_path
    end
  end

  private
  def skill_params
    params.require(:skill).permit(:title, :description, :workshop_id)
  end

  def set_skill
    @skill = Skill.find_by(id: params[:id])
  end

end

app/views/skills/_form.html.erb
<%= form_for [@workshop, @skill] do |f| %>
<% if @skill.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= f.hidden_field :workshop_id %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Which workshop is this for?" %>
    <%= f.collection_radio_buttons :workshop_id, Workshop.all, :id, :name do |b| %>
      <%= b.label(class: 'card') {b.radio_button + b.text}%>
    <%end%>
  </div>

  <% if controller.action_name == 'new'%>
    <%= f.submit "Create New Skill" %>
  <% else%>
    <%= f.submit "Update Skill" %>
    <%= link_to "Remove Skill", destroy_skill_path(@skill), :method => :delete, class: "btn btn-danger"  %>
  <%end%>
<%end%>

app/views/skills/_skill_form.html.erb
<%= form_for @skill do |f| %>
<% if @skill.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= f.hidden_field :workshop_id %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Which workshop is this for?" %>
    <%= f.collection_radio_buttons :workshop_id, Workshop.all, :id, :name do |b| %>
      <%= b.label(class: 'card') {b.radio_button + b.text}%>
    <%end%>
  </div>

  <%= f.submit "Update Skill", url: workshop_skill_path(:workshop_id, @skill)  %>
  <%= link_to "Remove Skill", skill_path(@skill), :method => :delete, class: "btn btn-danger"  %>
<%end%>

app/views/skills/_workshop_skill_form.html.erb
<%= form_for [@workshop, @skill] do |f| %>
<% if @skill.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= f.hidden_field :workshop_id %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Which workshop is this for?" %>
    <%= f.collection_radio_buttons :workshop_id, Workshop.all, :id, :name do |b| %>
      <%= b.label(class: 'card') {b.radio_button + b.text}%>
    <%end%>
  </div>

  <% if !@skill.persisted?%>
    <%= f.submit "Create New Skill", url: new_workshop_skill_path(@workshop) %>
  <% else%>
    <%= f.submit "Update Skill", url: edit_workshop_skill_path(@workshop, @skill)  %>
    <%= link_to "Remove Skill", workshop_skill_path(@workshop, @skill), :method => :delete, class: "btn btn-danger"  %>
  <%end%>
<%end%>

app/views/skills/edit.html.erb
<% if !!@workshop %>
  <%= render 'workshop_skill_form' %>
<% else %>
  <%= render 'skill_form' %>
<% end %>

app/views/skills/new.html.erb
  <%= render 'workshop_skill_form' %>

app/views/skills/show.html.erb
<%= render 'form' %>