config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'application#index'
  resources :users, only: [:index]
  post '/users/search_by', to: 'users#search_by'
  get '/users/new', to: 'admin/users#new'
  get '/workshops/new', to: 'admin/workshops#new'

  authenticate :user do
    resources :users, only: [:show]
    resources :skills, only: [:edit, :destroy]
    resources :workshops, except: [:new, :create] do
      resources :skills, only: [:new, :create, :edit, :update, :destroy]
      resources :users, only: [:show, :edit, :update]
    end
  end

  namespace :admin  do
    resources :users, only: [:show, :edit, :update]
    resources :workshops, only: [:new, :create, :edit, :update]
  end
end

app/models/user.rb
class MyValidator < ActiveModel::Validator
  def validate(record)
    unless !record.name.nil?
      record.errors[:name] << "cannot be blank"
    end
  end
end

class User < ApplicationRecord
  include ActiveModel::Validations
  validates_with MyValidator

  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :workshops, through: :skills
  enum role: [:member, :admin]

  validates :name, format: { without: /[0-9]/, message: "does not allow numbers" }
  validates :email, uniqueness: true

  accepts_nested_attributes_for :skills, allow_destroy: true,  :reject_if => proc { |attributes| attributes['title'].blank? }
  accepts_nested_attributes_for :user_skills, allow_destroy: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

   def user_skills_attributes=(user_skills_attributes)
     user_skills_attributes.values.each do |user_skill_attributes|
       user_skill = UserSkill.find_by(id: user_skill_attributes[:id])
       if !!user_skill
         user_skill.skill_level = user_skill_attributes[:skill_level]
         user_skill.save
       end
     end
   end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end

  def self.find_for_slack(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end

  def self.total_members
    count
  end

  def self.search_by(field, value)
    where(field => value)
  end

  def self.search_terms
    ['id','name','email']
  end

  def allowed_workshops
    allowed = workshops.collect { |workshop| workshop.skills.all? { |skill| self.skills.include?(skill) } ? workshop : nil}.compact.uniq
    allowed << Workshop.select { |shop| shop.officer == self}
    allowed.flatten.uniq.sort_by(&:name)
  end

  def skill_level(skill)
      user_skill = UserSkill.find_by(user_id: self.id, skill_id: skill.id)
      if !user_skill
        :unskilled
      else
        user_skill.skill_level
      end
  end

  def has_workshop(workshop)
    if allowed_workshops.include?(workshop) || workshop.skills.empty?
      "skilled"
    else
      "unskilled"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :allowed?]
  before_action :set_workshop, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User created successfully'
    else
      render action: 'new', alert: "Creation failed:  #{@user.errors.full_messages}"
    end
  end

  def show
    @workshops = Workshop.all.sort_by(&:name)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User updated'
    else
      render action: 'edit', alert: "Update failed:  #{@user.errors.full_messages}"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :skill_ids =>[], :user_skills_attributes => [:skill_level, :id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_workshop
    @workshop = Workshop.find_by(id: params[:workshop_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :allowed?]
  before_action :set_workshop, only: [:edit]
  before_action :allowed?, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @workshops = Workshop.all.sort_by(&:name)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User updated'
    else
      render action: 'edit', alert: "Update failed:  #{@user.errors.full_messages}"
    end
  end

  def search_by
    if params[:value].empty?
      redirect_to users_path and return
    else
      @users = User.search_by(params[:field], params[:value])
      render 'index' and return
    end
  end

  private
  def user_params
    binding.pry
    params.require(:user).permit(:name, :email, :skill_ids =>[], :user_skills_attributes => [:skill_level, :id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_workshop
    @workshop = Workshop.find_by(id: params[:workshop_id])
  end

  def allowed?
    set_workshop
    unless current_user.try(:admin?) || @user == current_user || @workshop.try(:officer) == current_user
      redirect_to root_path, alert: "You are not allowed to access that page."
    end
  end
end

app/views/admin/users/_form.html.erb
<div class="form-group">

<%= form_for [:admin, @user] do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <h4><%= f.label :name %>
      <%= f.text_field :name %> </h4>
    </div>

    <h4><%= f.label 'Skills:' %> </h4>
    <% Workshop.all.each do |workshop| %>
      <h5>Workshop: <%= f.label workshop.name %> </h5>

      <div class="well">
        <%= f.collection_check_boxes(:skill_ids, workshop.skills, :id, :title) do |b| %>
          <ul>
          <%=  b.label(:"data-value" => b.value) { b.check_box + b.text } %>

          <% if f.object.skills.include?(b.object) %>
            <%= f.fields_for :user_skills do |ff| %>
                <% if ff.object.skill == b.object %>
                  <%= ff.select(:skill_level, [:novice, :pro, :expert]) %>
                <% end %>
            <% end %>
          <%end %>
          </ul>
        <% end %>
      </div>
    <% end %>
  <br>
  <%= f.submit "Update User", url: admin_user_path(@user), :method => :put  %>
<% end %>

</div>

app/views/admin/users/edit.html.erb
  <%= render 'form' %>

app/views/admin/users/new.html.erb
New User Creation restricted at this time.

app/views/admin/users/show.html.erb
<div class="row shadow">
  <div class="col-sm-12">
    <h2><%= @user.name %> </h2>
    <h3><%= @user.email %> </h3>
    <% if is_admin? %>
      <%= link_to "Edit", edit_admin_user_path(@user), class: "btn btn-primary card"  %>
    <% end %>

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <% @workshops.each do |workshop| %>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading<%=workshop.id%>">
          <h4 class="panel-title <%=@user.has_workshop(workshop)%>">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=workshop.id%>" aria-expanded="false" aria-controls="collapse<%=workshop.id%>">
              <%=workshop.name %>
              <%= is_officer?(workshop) ? (link_to "Train", edit_workshop_user_path(workshop),  class: "btn btn-info") : ""%>
            </a>
          </h4>
        </div>
        <div id="collapse<%=workshop.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=workshop.id%>">
          <div class="panel-body">
            <% if workshop.skills.empty? %>
              <%= "No skills requried for #{workshop.name}" %>
            <% else %>
              <% workshop.skills.each do |skill| %>
                <li class="<%=@user.skill_level(skill)%>"><%= skill.title %></li>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>